### ISSUE TITLE
Map changelevel problem

### ISSUE THREAD

**Issue by yzybb** [fdxx/cutlrbtreefix#3]
Hello fdxx, why does the old version solve the problem without reloading the map, while the new version requires reloading the map instead? This has a slight impact on the player experience because when reloading the map, the player's screen is black and they do not know what is happening.

**Comment by fdxx** [comment]
"CUtlRBTree overflow" can still occur during gameplay.
For example, if you been playing in one chapter for a long time, and keep team wipeout and restarted. the game's garbage string data will continue to accumulate.
When the limit is exceeded, the server will crash immediately and will not wait until the map transitions.

**Comment by yzybb** [comment]
Thank you for your reply. I know, I'm talking about the old version of your extension. Since version 0.2, you have introduced the automatic map reload feature. Prior to version 0.2, you did not need to reload the map and could fix the "CUTlRBTree overflow" issue.

**Comment by fdxx** [comment]
>Prior to version 0.2, you did not need to reload the map and could fix the "CUTlRBTree overflow" issue.

Not fully fixed.

> When the limit is exceeded, the server will crash immediately and will not wait until the map transitions.

So we reset the current map when the game is about to crash in order to auto clear the string pool.
