### ISSUE TITLE
Unable to locate the program input point RtlPcToFileHeader

### ISSUE THREAD

**Issue by Fripine** [fdxx/cutlrbtreefix#4]
Thank you for providing such a useful extension.

When I installed the ext (**version 0.3**) and started my server, an error occurred: **Unable to locate the program input point RtlPcToFileHeader in the dynamic link library cutlrbtreefix.ext.2.l4d2.dll**

But everything worked fine after I rolled it back to **version 0.2**

My server is running with **sourcemod 1.11** on **Windows 2012r2**

Hope to find a solution that can install and run the latest version

![image](https://github.com/user-attachments/assets/62c04446-5f00-470f-aa06-475217ddcd3f)

**Comment by fdxx** [comment]
Windows 2012 is not supported. The extension is now built with c++17.

Currently sourcemod-1.12 is also built with c++17. If you use **pure** sourcemod-1.12, you will also encounter this problem.
https://github.com/alliedmodders/sourcemod/blob/8690afc1595028d18b7827fbb2831a195a3eacc6/AMBuildScript#L185

You need to use **Windows 2016** or later to run.
